### ISSUE TITLE
无法找到GstreamerMediaPlayerAgent

### ISSUE THREAD

**Issue by bingzijian** [iFLYOS-OPEN/SDK-Linux#1]
编译成功后，并没有发现GstreamerMediaPlayerAgent

**Comment by jan4984** [comment]
请阅读README，https://github.com/iFLYOS-OPEN/SDK-Linux#%E6%8B%B7%E8%B4%9Diflyos%E5%88%B0%E6%A0%91%E8%8E%93%E6%B4%BE “如需替换MicAgent或IFLYOSUmbrella,则用自己编译的程序覆盖”。目前只开放这两个可执行程序的可编译源码。

**Comment by bingzijian** [comment]
在release包里有，谢谢
